# -*- mode: ruby -*-

# frozen_string_literal: true

# taps
tap "aws/tap"
tap "borkdude/brew"
tap "clojure/tools"
tap "coursier/formulas"
tap "d12frosted/emacs-plus"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "oven-sh/bun"
tap "sdkman/tap"
tap "teamookla/speedtest"
tap "turbot/tap"

# packages #
brew "apache-spark"
brew "aspell"
brew "autoconf"
brew "automake"
brew "aws-sam-cli"
brew "awscli"
brew "bat" # cat with wings
brew "borkdude/brew/babashka"
brew "borkdude/brew/clj-kondo"
brew "bun"
brew "clojure-lsp"
brew "clojure/tools/clojure"
brew "cmake"
brew "coreutils"
brew "coursier/formulas/coursier"
brew "d12frosted/emacs-plus/emacs-plus@30", args: ["with-debug", "with-mailutils", "with-modern-icon", "with-native-comp", "with-xwidgets", "with-imagemagick", "with-poll"]
brew "direnv"
brew "dog"
brew "exercism"
brew "fd"
brew "figlet"
brew "fish"
brew "gcc"
brew "gh"
brew "git"
brew "git-crypt"
brew "git-delta"
brew "git-lfs"
brew "glib"
brew "gnupg", link: false
brew "gnutls"
brew "go"
brew "gping"
brew "gradle"
brew "graphviz"
brew "grep"
brew "guile"
brew "hadolint"
brew "harfbuzz"
brew "helm"
brew "htop"
brew "httpie"
brew "imagemagick"
brew "janet" # janet-lang, like clojure
brew "jq"
brew "kafka"
brew "kubectx"
brew "languagetool"
brew "lapack" # linear algebra
brew "leiningen"
brew "libgccjit"
brew "libheif"
brew "libproxy"
brew "libraw"
brew "librdkafka"
brew "librsvg"
brew "libssh2"
brew "llvm"
brew "lolcat"
brew "lsd"
brew "luv" # libuv bindings for lua
brew "mailutils"
brew "markdown"
brew "maven"
brew "mermaid-cli"
brew "neovim"
brew "nghttp2"
brew "node"
brew "oauth2l"
brew "openblas"
brew "p11-kit"
brew "pango" # text rendering
brew "pkg-config"
brew "plantuml"
brew "podman"
brew "poetry"
brew "poppler"
brew "procs"
brew "pstree"
brew "pyenv"
brew "pyenv-virtualenv"
brew "qt"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "roswell"
brew "rover"
brew "ruby-build"
brew "rustup-init"
brew "sbcl"
brew "sbt"
brew "scala"
brew "sdkman-cli"
brew "shared-mime-info"
brew "starship"
brew "structurizr-cli"
brew "teamookla/speedtest/speedtest"
brew "terracognita"
brew "terraform-docs"
brew "terraform-ls"
brew "texinfo"
brew "tfenv"
brew "tfsec"
brew "tig"
brew "tldr"
brew "tmux"
brew "tree"
brew "tree-sitter"
brew "turbot/tap/steampipe"
brew "unbound"
brew "vale"
brew "wget"
brew "yarn"
brew "zlib"
brew "zoxide"

# casks #

# set arguments for all "brew cask " commands
cask_args appdir: "/Applications", require_sha: true

cask "alacritty"
cask "authy"
cask "canva"
cask "confluent-cli"
cask "dashlane"
cask "dbeaver-community"
cask "docker"
cask "drawio"
cask "dropbox"
cask "firefox"
cask "flutter"
cask "font-fira-code"
cask "font-fira-mono-nerd-font"
cask "font-hack-nerd-font"
cask "font-sauce-code-pro-nerd-font"
cask "gitter"
cask "google-chrome",  args: { require_sha: false }
cask "google-drive",  args: { require_sha: false }
cask "gpg-suite"
cask "intellij-idea-ce"
cask "jprofiler"
cask "keybase"
cask "mactex"
cask "miro"
cask "pdf-expert"
cask "slack"
cask "spotify"
cask "todoist"
cask "virtualbox"
cask "visual-studio-code"
cask "zed"
